backend:
  name: git-gateway
media_folder: public/images
public_folder: /images
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Partners'
        name: 'partners'
        file: 'src/content/partners.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'About'
        name: 'about'
        file: 'src/content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Board Title', name: 'boardTitle', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Partner'
    name: 'partner'
    folder: 'src/content/partners'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Finnish Link', name: 'finnishLink', widget: 'string' }
      - { label: 'English Link', name: 'englishLink', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Event'
    name: 'event'
    folder: 'src/content/events'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Time',
          name: 'time',
          widget: 'datetime',
          format: 'DD.MM.YYYY',
          date_format: 'DD.MM.YYYY',
          time_format: false,
          required: false,
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Recurring', name: 'isRecurring', widget: 'boolean' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'TLDR', name: 'tldr', widget: 'markdown', hint: 'When?, Where?, Who?, How?' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Landing info'
    name: 'landinginfo'
    folder: 'src/content/landinginfos'
    create: true
    identifier_field: Title
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Board member'
    name: 'boardmember'
    folder: 'src/content/boardmembers'
    create: true
    identifier_field: Name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Status', name: 'status', widget: 'string' }
      - { label: 'Game', name: 'game', widget: 'string' }
      - {
          label: 'Order number',
          name: 'orderNumber',
          widget: 'number',
          value_type: 'int',
          min: 1,
          max: 20,
          hint: 'The order in which the board members are displayed. Smallest first.',
        }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
  - label: 'Album'
    name: 'album'
    folder: 'src/content/albums'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string', hint: 'Flickr etc. link to album' }
      - { label: 'Image', name: 'image', widget: 'image' }
