backend:
  name: git-gateway
media_folder: public/images
public_folder: public/images
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Partners'
        name: 'partners'
        file: 'src/content/partners.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Partners'
    name: 'partner'
    folder: 'src/content/partners'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Finnish Link', name: 'finnishLink', widget: 'string' }
      - { label: 'English Link', name: 'englishLink', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Events'
    name: 'event'
    folder: 'src/content/events'
    create: true
    identifier_field: name
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Time',
          name: 'time',
          widget: 'datetime',
          date_format: 'DD.MM.YYYY',
          time_format: false,
          required: false,
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Recurring', name: 'isRecurring', widget: 'boolean' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
