backend:
  name: git-gateway
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Landing'
        name: 'landing'
        file: 'content/landing.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Partners'
        name: 'partners'
        file: 'content/partners.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Partners'
        name: 'partners'
        folder: 'content/partners'
        create: true
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Finnish Link', name: 'finnishLink', widget: 'string' }
          - { label: 'English Link', name: 'englishLink', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
