name: Build docker image and deploy to Azure Container instance
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/ag-web-container:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/ag-web-container:latest

      - name: 'Run Azure webhook'
        run: |
          curl -X POST -H "Content-Type: application/json" --data '{"source": "GitHub", "reason": "Push to master"}' ${{ secrets.WEBHOOK_URL }}
